<?php
/**
 * @file
 * All hooks
 */

/**
 *  TODO's
 * 
 * - use sprites for the images
 * - add caching
 * - finetune spinner action
 * - Check user permissions
 * 
 */

/*
 * Implementing hook_permission
 */
function admintabs_permission() {
   return array(
    'use admintabs' => array(    // use the admin tabs
      'title' => t('Use Admin Tabs'),
      'description' => t('Use Admin Tabs in the frontend'),
    ),
    'configure admintabs' => array( // confiture the admin tabs
      'title' => t('Configure Admin Tabs'),
      'description' => t('Change settings for Admin tabs.'),
    ),
  );
}

/*
 *  Implementing hook_menu
 */
function admintabs_menu() {
  $items = array();
  $items['admin/config/admintabs/'] = array(
    'title' => 'Admin tabs',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('admintabs_settings_form'),
    'access arguments' => array('configure admintabs'),
    'file' => 'includes/admintabs.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  
  return $items;
}
/*
 * Implementation of hook_block_info
 */
function admintabs_block_info() {
  $blocks = array();
  
  $blocks['admintabs'] = array(
    'info' => t('Admin Tabs'),
    'region' => 'content',
    'status' => 1,
    'propertiers' => array(
        'administrative' => FALSE,
    ),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function admintabs_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'admintabs':
      module_load_include('inc', 'admintabs', 'includes/admintabs.helpers');
      $block['content'] = admintabs_block_render();
      break;
  }
  return $block;
}

/**
 * Implements hook_theme().
 */
function admintabs_theme($existing, $type, $theme, $path) {
  return array(
    'parent_tab' => array(
      'variables' => array(),
      'path' => drupal_get_path('module', 'admintabs') . '/theme',
      'file' => 'admintabs.theme.inc',
    ),
    'child_tab' => array(
      'variables' => array(),
      'path' => drupal_get_path('module', 'admintabs') . '/theme',
      'file' => 'admintabs.theme.inc',
    ),
    'translationlink' => array(
      'variables' => array(),
      
      'path' => drupal_get_path('module', 'admintabs') . '/theme',
      'file' => 'admintabs.theme.inc',
    ),
  );
}
